name: drupal8-composer
sharing:
  appserver:
    remote: /var/www/html
proxy:
  nginx:
    - port: 80/tcp
      default: true
    - port: 443/tcp
      default: true
      secure: true
services:
  appserver:
    type: php:7.0
    via: nginx
    ssl: true
    webroot: web
    config:
      server: config/nginx/drupal.conf
      conf: config/php/php.ini
    extras:
      - "cd $LANDO_MOUNT && composer install"
      - "cd $LANDO_MOUNT && composer drupal-scaffold"
  database:
    type: mariadb
    portforward: 3310
    creds:
      user: drupal
      password: drupal
      database: drupal
    config:
      confd: config/mysql
  index:
    type: solr:5.5
    core: drupal
    config:
      conf: config/solr
  node:
    type: node:6.10
    globals:
      grunt-cli: "latest"
tooling:
  composer:
    service: appserver
  php:
    service: appserver
    user: www-data
  drush:
    service: appserver
    cmd: /var/www/html/vendor/bin/drush
  drupal:
    service: appserver
    cmd: /var/www/html/vendor/bin/drupal
  mysql:
    service: database
    description: Drop into a MySQL shell
  node:
    service: node
  npm:
    service: node
  grunt:
    service: node
