# The name of my app
name: trivial-sharing

# Compose files to load
compose:
  - compose.yml

# My sharing configuration
sharing:

  # Sharing configuration for the `web` service defined in my compose files
  web:

    # The location of my webroot on my host, relative to my app root
    local: webroot1

    # The location of the webroot inside the `web` container
    remote: /usr/local/apache2/htdocs

    # Optional ownership configuration for my files inside the container webroot
    # Generally these should be owned by the user runing your webserver
    # These are the default values
    uid: 33
    user: www-data
    gid: 33
    group: www-data

  # Sharing configuration for the `web2` service defined in my compose files
  # Generally you will not have a second webroot, shown only as an example
  web2:
    local: webroot2
    remote: /usr/share/nginx/html

# Proxy settings
proxy:
  web:
    - port: 80/tcp
      default: true
  web2:
    - port: 80/tcp
      subdomains:
        - web2
