name: trivial-sharing
compose:
  - compose.yml
sharing:
  web:
    local: webroot1
    remote: /usr/local/apache2/htdocs
    uid: 33
    user: www-data
    gid: 33
    group: www-data
  web2:
    local: webroot2
    remote: /usr/share/nginx/html
proxy:
  web:
    - port: 80/tcp
      default: true
  web2:
    - port: 80/tcp
      subdomains:
        - web2
