# The name of my app
name: trivial-sharing

# Compose files to load
compose:
  - compose.yml

# My sharing configuration
sharing:

  # Sharing configuration for the `web` service defined in my compose files
  web:

    # Share your app inside the `web` container at the following address
    # If your webroot is in a subdirectory, consult the specific service eg `php`
    # on how to configure a nested docroot
    remote: /usr/local/apache2/htdocs

    # Optional ownership configuration for my files inside the container webroot
    # Generally these should be owned by the user runing your webserver
    # These are the default values
    uid: 33
    user: www-data
    gid: 33
    group: www-data

# Proxy settings
proxy:
  web:
    - port: 80/tcp
      default: true

