name: lando-tooling
compose:
  - compose.yml
events:
  post-start:
    - node: whoami | grep node
services:
  node:
    type: node:12
tooling:
  busted:
    service: web
    cmd: i-do-not-exist
  dynamic:
    cmd: env
    service: :service
    options:
      service:
        default: web
        alias:
          - s
        describe: Run a different service
  env:
    cmd:
      - php: env
      - web: env
    description: Print environment variables for a few things
  iamroot:
    service: php
    cmd: echo "$HOME" && echo "$(id)" > /whoami
    user: root
  nodeme:
    service: node
    cmd: whoami
  notme:
    service: node
    cmd: whoami
    user: www-data
  pipesandstuff:
    service: node
    cmd:
      - env | grep LANDO_ > pipe.txt
      - echo "more" >> pipe.txt
  php:
    service: php
    description: Run php commands
    cmd: php
  stillme:
    cmd:
      - node: whoami
  test:
    service: php
    cmd:
      - php -v
      - php -m
    description: Run all the tests
  whoami:
    service: php
    cmd: id
  word:
    service: web
    cmd: /app/word.sh
    level: app
    options:
      word:
        passthrough: true
        alias:
          - w
        describe: Print what the word is
        interactive:
          type: input
          message: What is the word?
          default: bird
          weight: 600
  wraptest:
    service: web
    user: root
    cmd: echo "$(ls -lsa /*)"
