name: lamp
sharing:
  appserver:
    local: www
    remote: /var/www/html
proxy:
  appserver:
    - port: 80/tcp
      default: true
    - port: 443/tcp
      default: true
      secure: true
services:
  appserver:
    type: php:5.6
    via: apache
    ssl: true
  database:
    type: mysql
    portforward: 3308
    creds:
      user: lamp
      password: lamp
      database: lamp
