# LAMP stack example
name: lamp

# Share my app into apache's webroot
sharing:
  appserver:
    remote: /var/www/html

# Give me http://lamp.lndo.site and https://lamp.lndo.site
proxy:
  appserver:
    - port: 80/tcp
      default: true
    - port: 443/tcp
      default: true
      secure: true

# Spin up services to run a basic LAMP stack
services:

  # Create a php 5.6 instance served by the latest apache with https turned on
  appserver:

    # PHP version 5.6
    type: php:5.6

    # Serve php by either apache or nginx. You can put in any `service:version`
    # string that is supported by Lando's nginx and apache services.
    via: apache

    # Optionally serve php over https
    ssl: true

    # Optionally specify a webroot if it is a subdirectory of the appRoot
    webroot: www

    # Optionally customize the configuration for php and its underlying webserver
    # These paths are both relative to the app root directory
    # config:
      # Use a custom apache config file
      # server: config/apache/lamp.conf

      # Use a custom php.ini
      # conf: config/php/php.ini

    # Optionally install the following composer dependencies globally
    # These follow the normal composer.json form
    # Note that many composer dependencies should not be installed globally but
    # on a per-project basis
    # composer:
    #   drush/drush: "~8"

    # Optionally run the following build steps
    # build:
    #  - "cd $$LANDO_MOUNT && composer install"

    # Optionally install additional server software
    # extras:
    #  - "apt-get update -y"
    #  - "apt-get install netcat -y"

  # My database service
  database:
    type: mysql
    portforward: 3308
    creds:
      user: lamp
      password: lamp
      database: lamp

# Add some nice command routing
tooling:
  composer:
    service: appserver
    description: Run composer commands
    cmd:
      - composer
      - --ansi
  php:
    service: appserver
  mysql:
    user: root
    service: database
    description: Drop into a MySQL shell
