# phpcli example
name: phpcli

# Spin up a php cli
services:

  # Create a php 7.1 cli
  phpcli:

    # PHP version 7.1
    type: php:7.1

    # Set to run in CLI mode
    via: cli

    # Optionally install the following composer dependencies globally
    # These follow the normal composer.json form
    # Note that many composer dependencies should not be installed globally but
    # on a per-project basis
    # composer:
    #  overtrue/phplint: '*'

    # Optionally run the following commands after the service is started
    # Runs composer install but dont fail on an error
    # run:
    #  - "cd $LANDO_MOUNT && composer install || true"

    # Optionally activate xdebug
    #
    # If you are having trouble getting xdebug to work please see:
    # https://docs.devwithlando.io/services/php.html#using-xdebug
    xdebug: true

    # Optionally mix in your own config files
    #
    # If ommitted this will use "sane defaults" for your recipe type
    # conf:

      # For more information on setting these files check out the documentation
      # and examples
      #
      # Docs: https://docs.devwithlando.io/services/php.html
      # Examples: https://github.com/lando/lando/tree/master/examples
      #
      # php: config/php.ini

# Add some nice command routing
tooling:
  composer:
    service: phpcli
    description: Run composer commands
    cmd:
      - composer
      - --ansi
  php:
    service: phpcli
