product: lando
channel: stable
domain: lndo.site
mode: cli

dockerSupported:
  dockerCompose: '1.23-1.25'
  dockerDesktop: '2.1.0.0-2.2.0.5'
  dockerEngine: '19'
dockerTolerance: patch

landoFile: .lando.yml
stats:
  - report: true
    url: https://metrics.lando.dev
