plugins:
  - lando-app
  - lando-core
  - lando-engine
  - lando-events
  - lando-init
  - lando-networking
  - lando-proxy
  - lando-recipes
  - lando-services
  - lando-tooling
stats:
  - report: true
    url: https://metrics.devwithlando.io
