# Dockerfile example
name: dockerfile

# Start with the default LEMP recipe
recipe: lemp

# Override the recipe image with a build location
services:
  appserver:

    # You probably want to set this to custom
    type: php:custom
    overrides:
      services:

        # This should relative to your app root
        build: ./php

        # Optionally specify a name and tag for the built image so you can
        # user it elsewhere later
        #
        # NOTE: Docker may throw a warning like:
        #   WARNING: Image for service appserver was built because it did not already exist.
        # This is safe to ignore
        image: pirog/php:7.1-fpm-custom

        # This is not needed it only serves to illustrate how you can map internal container things
        # to your app directory for easy editability
        volumes:
          - ./config/custom.ini:/usr/local/etc/php/conf.d/zzzz-custom.ini
          - ./logs:/var/logs
