version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
      # @todo: once we have more tests running lets buy the below and
      # set up max parallelism
      # docker_layer_caching: true
    parallelism: 8
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: Get PPAz
          command: |
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash
            curl -fsSL -o /tmp/lando.deb http://installer.kalabox.io/lando-latest-dev.deb
      - run:
          name: Update deps
          command: sudo apt-get update -y
      - run:
          name: Install deps
          command: |
            sudo rm -rf /var/lib/apt/lists/lock
            sudo rm -rf /var/cache/apt/archives/lock
            sudo rm -rf /var/lib/dpkg/lock
            sudo apt-get install -y nodejs yarn cgroup-bin curl
      - run:
          name: Install node modules
          command: yarn
      - run:
          name: Verify we have the things we need to start
          command: |
            docker -v
            docker-compose -v
            node -v
            yarn -v
            node ~/project/bin/lando.js version
      - run:
          name: Install latest lando
          command: |
            sudo rm -rf /var/lib/apt/lists/lock
            sudo rm -rf /var/cache/apt/archives/lock
            sudo rm -rf /var/lib/dpkg/lock
            sudo dpkg -i /tmp/lando.deb
            cp -f ~/project/.circleci/lando.yml ~/project/config.yml
            node ~/project/bin/lando.js config
      - run:
          name: Run func test
          command: |
            node ~/project/scripts/generate-tests.js
            echo $(circleci tests split ~/project/test/func/split-file.txt)
            mocha --timeout 900000 $(circleci tests split ~/project/test/func/split-file.txt)
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
