name: lando-node-12
services:
  defaults:
    type: node:12
    build:
      - yarn
    command: /app/node_modules/.bin/nodemon src/app-http.js --watch src --ignore *.test.js
  custom:
    type: node:13
    ssl: true
    globals:
      gulp-cli: latest
    port: 3000
    build:
      - yarn
    command: /app/node_modules/.bin/nodemon src/app-https.js --watch src --ignore *.test.js
  custom2:
    type: node:12.4
    ssl: 4444
    port: 3000
    build:
      - yarn
    command: /app/node_modules/.bin/nodemon src/app-custom.js --watch src --ignore *.test.js
  patch:
    type: node:12.13.1
  cli:
    type: node
