name: lando-proxy
compose:
  - compose.yml
proxy:
  web:
    - lando-proxy.lndo.site
    - sub.lando-proxy.lndo.site
    - bob.frank.kbox.com
    - frank.bob.joe
    - tippecanoe.tyler.too
    - lets.see.what.happens.in.a.lndo.site/subdir
    - or.in.a.deeper.lndo.site/subdirectory/tree/
  web2:
    - another-way-to-eighty.lndo.site:80
    - lando-proxy.lndo.site/api
    # - andonemore.lndo.site:8000
    # - db.lndo.site:3306
    - "*-lando-proxy.lndo.site"
    - "wild.*.lando-proxy.lndo.site"
  web3:
    - "lets.combine.*.lndo.site:8080/everything/for-real"
    - web3.lndo.site:8080
services:
  web3:
    type: compose
    services:
      image: bitnami/nginx
      command: /opt/bitnami/scripts/nginx/entrypoint.sh /opt/bitnami/scripts/nginx/run.sh
      volumes:
        - "./:/app"
      ports:
        - "8080"
