# New build process example
name: nbp

# Give me http://nbp.lndo.site and https://nbp.lndo.site
proxy:
  appserver:
    - nbp.lndo.site

# Spin up services to run a basic node server
services:

  # Create a node instance
  appserver:

    # Node version 6.10
    type: node:6.10

    # Optionally create certs in /certs that can be used by your application
    # to listen over https. Creates the following certs your app can use
    #
    #   - /certs/cert.key
    #   - /certs/cert.crt
    #   - /certs/cert.pem
    #
    ssl: true

    # Optionally install the following npm dependencies globally
    # These follow the normal package.json form
    #
    # Note that most deps should be installed by the normal npm install, this is
    # for things like gulp/grunt cli that are global dependencies
    globals:
      gulp-cli: "latest"

    # Optionally specify a command to run when you start your node service up.
    #
    # If you are using node as a server you are going to want to define this.
    # This can be either a string or array.
    #
    # If you are just spinning up a node container to run front end dependencies
    # you can leave this blank and the container will boot up and stay on
    #
    # You will likely want to run `lando npm install` first so needed dependencies are
    # installed before your server starts up.
    #
    command: npm start

    # Install server dependencies and packages that your app needs to run
    # These run BEFORE your app boots up and are things that require root access
    # Installing extra php extensions is a good example
    install_dependencies_as_root:
      - apt-get update -y
      - apt-get install vim -y

    # Install app dependencies and packages that your app needs to run
    # These also run BEFORE your app boots up but are things you don't want to
    # install as root.
    # Running `npm install` or `yarn` is a good example
    install_dependencies_as_me:
      - yarn

    # We encourage you to use events to automate commands that should run AFTER
    # your app starts eg a watch task

    # DEPRECATED BUILD STEPS, these will still run as they did pre-RC1 but we
    # HIGHLY ENCOURAGE you to move to the new build step format above.
    #
    # See https://docs.devwithlando.io/config/build.html#build-steps
    #
    # Note that *_internal steps should not be invoked like they are here
    # these channels are meant only for lando to use programmatically
    run_as_root_internal:
      - echo "run as root internal $(whoami)"
    run_as_root:
      - echo "run as root $(whoami)"
    extras:
      - echo "extras $(whoami)"
    run_internal:
      - echo "run internal $(whoami)"
    run_root:
      - echo "run $(whoami)"
    build:
      - echo "build $(whoami)"

# Add some nice command routing
tooling:
  npm:
    service: appserver
  node:
    service: appserver
  yarn:
    service: appserver

  # This should be available ONLY AFTER you start up the app since it gets installed
  # globally in the `globals` key in the appserver definition above
  gulp:
    service: appserver

  # Extra commands for fun
  vim:
    service: appserver
