name: nginx
sharing:
  appserver:
    local: www
    remote: /usr/share/nginx/html
proxy:
  appserver:
    - port: 80/tcp
      default: true
    - port: 443/tcp
      default: true
      secure: true
services:
  appserver:
    type: nginx:1.8.1
    ssl: true
    config:
      server: config/server.conf
    compose:
      environment:
        THING: STUFF
      ports: ['8080:80']
