# My apps name
name: trivial-proxy-legacy

# Docker compose files that contain my apps services and tools
compose:
  - compose.yml

# Proxy settings for my services
proxy:

  # Proxy settings for the "web" service defined inside my compose.yml.
  # NOTE: You can specify more than one service.
  web:

    # A port to proxy (generally this will be 80 or 443)
    - port: 80/tcp

      # Points `http://trivial-proxy.lndo.site` to your app
      default: true

      # Also points `http://{site1|site2|site3|site4}.trivial-proxy.lndo.site` to your site
      subdomains:
        - site1
        - site2
        - site3
        - site4

      # Set this to true if you want to access these addresses over https.
      # You will need to make sure the underlying service is set up to do this.
      # secure: true

      # Points the below addresses to your site as well
      # NOTE: You likely will want to add these to your /etc/hosts file so that they
      # point to 127.0.0.1
      custom:
        - bob.frank.kbox.com
        - frank.bob.joe
        - tippecanoe.tyler.too
