name: drupal7
proxy:
  nginx:
    - drupal7.lndo.site
services:
  appserver:
    type: php:5.6
    webroot: www
    via: nginx
    ssl: true
    config:
      server: config/nginx/drupal.conf
      conf: config/php/php.ini
    composer:
      drush/drush: "~8"
  database:
    type: mariadb
    portforward: 3310
    creds:
      user: drupal
      password: drupal
      database: drupal
    config:
      confd: config/mysql
  node:
    type: node:6.10
    globals:
      grunt-cli: "latest"
tooling:
  drush:
    service: appserver
    needs:
      - database
  composer:
    service: appserver
    description: Run composer commands
    cmd:
      - composer
      - --ansi
  php:
    service: appserver
  mysql:
    service: database
    description: Drop into a MySQL shell
    user: root
  node:
    service: node
  npm:
    service: node
  grunt:
    service: node
