language: php
php:
- '7.0'
services:
- docker

env:
  global:
    secure: a2uFRYTdRT6KqTTHSp97pqp+Dna1tQY9i5FVNHcBlwksEpViVXI3TxoXh1sB4szcqVflxrjnpYWycy4RTKYWr+Nhv4yMV5FmrLQ8iJM7MCSEQYP14HsQXTj6B8pA9sMFq7+qIgzOnJ/BwUh4YTrSAFXfeulE4PA0C+Nz55TUCqaB2B0Hvq6lD6gdQade99Yqeh6zeXZbtAaB0sEjZmQ/idGyC0vmSxTbdCOc9AzPwszdCrDxYJ+VCX+OjIgH+Y4i2NddMtlOs/mrHRck4xxMfjVuTLtLeUQlPaXIJM2MHQU9KY9itZDsNZE3bmJF4PwZ/7Yw7M4peR73t+ZxTSpxshKVovmXkdjeqzMiduvu7cpUJzmjCtEbrfWNesVtnwz2RfxgeEhZhpjb6UhTP2FEwD7L0P5gzQPgqvxNBLEBleWVVQrNuD0a4oEI+YP1evcjEnMRtlfUqskb5N379HIjZRmqthrle+V1fvFLqWA67hgIc5gz22DRA1l+RA6alCiGtUQJ92okc3/FVjNpR9OE2viWRc5kilP+xQX0tlOpRd+pmb185KCNvAzPTowpX5nI9SmJrJlNeFJbkk2A75TdiSdYfZEJkKECrn8yM6Sli+M0gr8IJ26WMMX58mvXVXr5NM9ve1iOzru24RZhuur85wgj+kmB1rS5uGCWo6fHG3A=

before_install:
- sudo apt-get -y update
- sudo apt-get -y install cgroup-bin curl
- curl -fsSL -o /tmp/lando-latest.deb http://installer.kalabox.io/lando-latest-dev.deb
- sudo dpkg -i /tmp/lando-latest.deb

script:
# start lando and perform some setup tasks.
- lando start -- -v
- lando version
- cd /home/travis/build/serundeputy/ci-tutorial/
- lando composer install
- cp travis/settings.local.php sites/default/settings.local.php

# Get the DB and install.
- lando terminus auth:login --machine-token=$TRAVISCITOKEN
- lando terminus backup:create ci-tutorial.dev --element=db
- lando terminus backup:get ci-tutorial.dev --element=db --to=/app/db.sql.gz
- lando db-import db.sql.gz

# Check if we can bootstrap the site.
- lando drush cr | grep "rebuild complete."

# Run phplint codecheck.
- lando composer test

# Run Behat tests.
- lando composer behat
