# Backdrop recipe
name: backdrop

# Start with the default Backdrop recipe
recipe: backdrop

# Configure the Backdrop recipe
config:

  # See: https://backdropcms.org/requirements

  # Optionally specify the php version to use.
  #
  # If ommitted this will default to the latest php version supported by Backdrop.
  # Consult the `php` service to see what version are available
  #
  # NOTE: that this needs to be wrapped in quotes so that it is a string
  php: '7.0'

  # Optionally specify whether you want to serve backdrop via nginx or apache
  #
  # If ommitted this will default to the latest apache
  # via: nginx

  # Optionally specify the location of the webroot relative to your approot.
  #
  # If ommitted this will be your approot itself.
  webroot: www

  # Optionally specify the version of backdrush you want for your site
  #
  # If ommitted this will use the stable backdrush
  backdrush: stable

  # Optionally specify the database type, this can be one of:
  #
  #   - `mysql`
  #   - `mariadb`
  #
  # If ommitted this will default to the latest mysql. You can additionally provide
  # a version with `type:version` but you will need to consult the documentation
  # for the correct DB service to see what versions are available
  # database: mariadb:10.1

  # Optionally mix in your own config files
  #
  # If ommitted this will use the default drupal config files for the respective
  # services. Definitely consult the relevant documentaion for each service to
  # make sure you are specifying the correct value for the config.
  # conf:
    # server: config/backdrop.conf
    # database: config/mysql
    # php: config/php.ini

# The Backdrop recipe is super slick but we want to augment this recipe so we can
# run our front end tooling magix
services:
  node:
    type: node:6.10
tooling:
  node:
    service: node
  npm:
    service: node
