# NODE server example
name: node

# Give me http://node.lndo.site and https://node.lndo.site
proxy:
  appserver:
    - port: 80/tcp
      default: true
    - port: 443/tcp
      default: true
      secure: true

# Spin up services to run a basic node server
services:

  # Create a node instance
  appserver:

    # Node version 6.10
    type: node:6.10

    # Optionally create certs in /certs that can be used by your application
    # to listen over https. Creates the following certs your app can use
    #
    #   - /certs/cert.key
    #   - /certs/cert.crt
    #   - /certs/cert.pem
    #
    ssl: true

    # Optionally install the following npm dependencies globally
    # These follow the normal package.json form
    #
    # Note that most deps should be installed by the normal npm install, this is
    # for things like gulp/grunt cli that are global dependencies
    globals:
      gulp-cli: "latest"

    # Optionally specify a command to run when you start your node service up
    # If you are using node as a server you are going to want to define this.
    # This can be either a string or array.
    #
    # If you are just spinning up a node container to run front end dependencies
    # you can leave this blank and the container will boot up and stay on
    #
    # You will likely want to use npm package.json scripts here so that you can
    # run `npm install` before your server starts up. Check out the package.json
    # in this example.
    command: npm start

    # Install our local package.json dependencies as part of a build step
    extras:
      - "cd $LANDO_MOUNT & npm install"

# Add some nice command routing
tooling:
  npm:
    service: appserver
  gulp:
    service: appserver
  node:
    service: appserver
