# Api
http://api.{default}/:
  type: upstream
  upstream: api:http
  cache:
    headers: ['Accept', 'Accept-Language', 'Origin']
    default_ttl: 299
    enabled: true
  ssi:
    enabled: false

# Blog
http://blog.devwithlando.io/:
  type: redirect
  to: http://blog.{default}/
http://blog.lndo.io/:
  type: redirect
  to: http://blog.{default}/
http://blog.{default}/:
  type: upstream
  upstream: blog:http
  cache:
    headers: ['Accept', 'Accept-Language', 'Origin']
    default_ttl: 2600
    enabled: true
  ssi:
    enabled: false

# Docs
http://docs.devwithlando.io/:
  type: redirect
  to: http://docs.{default}/
http://docs.lndo.io/:
  type: redirect
  to: http://docs.{default}/
http://docs.{default}/:
  type: upstream
  upstream: docs:http
  cache:
    headers: ['Accept', 'Accept-Language', 'Origin']
    default_ttl: 2600
    enabled: true
  ssi:
    enabled: false

# Events
http://events.devwithlando.io/:
  type: redirect
  to: http://events.{default}/
http://events.lndo.io/:
  type: redirect
  to: http://events.{default}/
http://events.{default}/:
  type: upstream
  upstream: events:http
  cache:
    headers: ['Accept', 'Accept-Language', 'Origin']
    default_ttl: 2600
    enabled: true
  ssi:
    enabled: false

# Metrics
https://stats.devwithlando.io/:
  type: upstream
  redirects:
    expires: -1s
    paths: {}
  cache:
    enabled: true
    default_ttl: 604800
    cookies:
    - '*'
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  upstream: metrics:http
https://metrics.devwithlando.io/:
  type: upstream
  redirects:
    expires: -1s
    paths: {}
  cache:
    enabled: true
    default_ttl: 604800
    cookies:
    - '*'
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  upstream: metrics:http
https://metrics.lndo.io/:
  type: upstream
  redirects:
    expires: -1s
    paths: {}
  cache:
    enabled: true
    default_ttl: 604800
    cookies:
    - '*'
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  upstream: metrics:http
https://stats.lndo.io/:
  type: upstream
  redirects:
    expires: -1s
    paths: {}
  cache:
    enabled: true
    default_ttl: 604800
    cookies:
    - '*'
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  upstream: metrics:http
http://stats.{default}/:
  type: upstream
  redirects:
    expires: -1s
    paths: {}
  cache:
    enabled: true
    default_ttl: 604800
    cookies:
    - '*'
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  upstream: metrics:http
http://metrics.{default}/:
  type: upstream
  redirects:
    expires: -1s
    paths: {}
  cache:
    enabled: true
    default_ttl: 604800
    cookies:
    - '*'
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  upstream: metrics:http
https://stats-v2.kalabox.io/:
  type: upstream
  redirects:
    expires: -1s
    paths: {}
  cache:
    enabled: true
    default_ttl: 604800
    cookies:
    - '*'
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  upstream: metrics:http

# Site
http://devwithlando.io/:
  type: redirect
  to: http://{default}/
http://lndo.io/:
  type: redirect
  to: http://{default}/
http://{default}/:
  type: upstream
  upstream: site:http
  cache:
    headers: ['Accept', 'Accept-Language', 'Origin']
    default_ttl: 2600
    enabled: true
  ssi:
    enabled: false
