# ASP app
name: asp

# Give me http://asp.lndo.site and https://asp.lndo.site
proxy:
  appserver:
    - asp.lndo.site

# Spin up services to run a basic asp server
services:

  # Create a asp instance
  appserver:

    # asp version 2.0
    type: asp:2.0

    # Optionally create certs in /certs that can be used by your application
    # to listen over https. Creates the following certs your app can use
    #
    #   - /certs/cert.key
    #   - /certs/cert.crt
    #   - /certs/cert.pem
    #
    # ssl: true

    # Optionally specify a command/script to run when you start your asp service up.
    #
    # If you are using asp as a server you are going to want to define this.
    # This can be either a string or array.
    #
    # If you are just spinning up a asp container for usage as a cli tool
    # you can leave this blank and the container will boot up and stay on
    #
    # You will likely want to run needed build steps eg `lando pip install`
    # first so needed dependencies are installed before your server starts up.
    #
    command: cd /app & dotnet run

    # Install some extra server packages
    # extras:
    #  - "apt-get update -y"
    #  - "apt-get install vim -y"

    # Print a message just to demonstrate this
    # build:
    # - "cd $LANDO_MOUNT & echo 'Holla!'"

# Add some nice command routing
tooling:

  # Any asp service with a defined command (aka not running in cli only mode)
  # Will also spin up a asp cli container called `SERVICENAME_cli` (appserver_cli)
  # in this example.
  #
  # This will allow you to run things like `lando dotnet publish` without needing
  # to `lando start` first.
  dotnet:
    service: appserver_cli
