# Example for a basic lemp stack with some extra tools installed
name: addtools
recipe: lemp
config:
  php: '7.1'
services:
  appserver:
    composer:
      phpunit/phpunit: '*'
    run_as_root:
      - "apt-get update -y"
      - "apt-get install build-essential chrpath libssl-dev libxft-dev libfreetype6-dev libfreetype6 libfontconfig1-dev libfontconfig1 -y"
      - "wget https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2"
      - "tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2 -C /usr/local/share/"
      - "ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/"
tooling:
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
  phantomjs:
    service: appserver
    description: "Run phantomjs commands"
  git:
    service: appserver
