name: trivial-services
sharing:
  appserver:
    local: www
    remote: /usr/share/nginx/html
proxy:
  appserver:
    - port: 80/tcp
      default: true
    - port: 443/tcp
      default: true
      secure: true
services:
  appserver:
    type: nginx:stable
    ssl: true
    config:
      server: config/server.conf
    overrides:
      services:
        environment:
          THING: STUFF
        ports: ['8080:80']
