# Drupal 8 recipe
name: d8

# Start with the default Drupal 8 recipe
recipe: drupal8

# Configure the Drupal8 recipe
config:

  # See: https://www.drupal.org/docs/7/system-requirements

  # Optionally specify the php version to use.
  #
  # If ommitted this will default to the latest php version supported by Drupal 8.
  # Consult the `php` service to see what versions are available. Note that all
  # such versions may not be supported in Drupal 8s so YMMV.
  #
  # See: https://www.drupal.org/docs/7/system-requirements/php
  #
  # NOTE: that this needs to be wrapped in quotes so that it is a string
  #
  php: '7.1'

  # Optionally specify whether you want to serve drupal via nginx or apache
  #
  # If ommitted this will default to the latest apache
  #
  # See: https://www.drupal.org/docs/7/system-requirements/web-server
  #
  via: nginx

  # Optionally specify the location of the webroot relative to your approot.
  #
  # If ommitted this will be your approot itself.
  #
  webroot: web

  # Optionally specify the version of global drush on your site
  #
  # If omitted this will install the latest stable version
  #
  # You should also highly consider a site-local install of drush.
  #
  # See: http://docs.drush.org/en/master/install/
  #
  # This will also grab any version to which there is a corresponding phar over
  # on the drush github release page eg `8.1.12` or "stable" for the latest
  # stable version
  #
  # See: https://github.com/drush-ops/drush/releases
  #
  drush: stable

  # Optionally specify whether you want a global install of drupal console.
  #
  # You should also consider a site-local install of drupal console via composer
  #
  # See: https://hechoendrupal.gitbooks.io/drupal-console/content/en/getting/composer.html
  #
  drupal: true

  # Optionally specify the database type, this can be one of:
  #
  #   - `mysql`
  #   - `mariadb`
  #   - `postgres`
  #
  # If ommitted this will default to the latest mysql. You can additionally provide
  # a version with `type:version` but you will need to consult the documentation
  # for the correct DB service to see what versions are available
  #
  # see: https://www.drupal.org/docs/7/system-requirements/database-server
  #
  # database: mariadb:10.1

  # Optionally mix in your own config files
  #
  # If ommitted this will use the default Drupal 8 config files for the respective
  # services.
  #
  # Definitely consult the relevant documentaion for each service to make sure
  # you are specifying the correct value for the config. As an example `mysql`
  # will want a directory while `postgres` will want a specific config file.
  #
  # conf:
    # server: config/drupal8.conf
    # database: config/mysql
    # php: config/php.ini

# The Drupal 7 recipe is super slick but we want to augment this recipe so we can
# run our front end tooling magix and use a key value store
services:
  node:
    type: node:6.10
  cache:
    type: redis
    persist: true
tooling:
  redis-cli:
    service: cache
  node:
    service: node
  npm:
    service: node
