name: lemp
sharing:
  appserver:
    local: www
    remote: /var/www/html
proxy:
  nginx:
    - port: 80/tcp
      default: true
    - port: 443/tcp
      default: true
      secure: true
services:
  appserver:
    type: php:7.1
    via: nginx
    ssl: true
    extras:
      - apt-get update
      - apt-get install vim -y
  database:
    type: mariadb
    portforward: true
