# LAMP recipe example
name: lamp2

# Start with the default LAMP recipe
recipe: lamp

# Configure the LAMP recipe
config:

  # Optionally specify the php version to use.
  #
  # If ommitted this will default to  the latest php version. Consult the `php`
  # service to see what version are available
  #
  # NOTE: that this needs to be wrapped in quotes so that it is a string
  php: '5.6'

  # Optionally specify the location of the webroot relative to your approot.
  #
  # If ommitted this will be your approot itself.
  webroot: www

  # Optionally specify the database type, this can be one of:
  #
  #   - `mysql`
  #   - `mariadb`
  #   - `postgres`
  #
  # If ommitted this will default to the latest mysql. You can additionally provide
  # a version with `type:version` but you will need to consult the documentation
  # for the correct DB service to see what versions are available
  database: mysql

  # Optionally activate xdebug
  xdebug: true

  # Optionally mix in our own config files
  #
  # If ommitted this will use the default config files for the respective services.
  # Definitely consult the relevant documentaion for each service to make sure
  # you are specifying the correct value for the config. As an example `mysql`
  # will want a directory while `postgres` will want a specific config file.
  conf:
    server: config/lamp.conf
    database: config/mysql
    php: config/php.ini
