# LAMP recipe example
name: lamp2
recipe: lamp
config:
  php: 5.6
  webroot: www
  database: mysql
  conf:
    #apache: config/lamp.conf
    database: config/mysql
    php: config/php.ini
services:
  node:
    type: node:6.10
tooling:
  node:
    service: node
  npm:
    service: node
